import turtle

screen = turtle.Screen()
screen.bgcolor("#0D0E47")
t = turtle.Turtle()

def eye():
    t.penup()
    t.goto(-1,-40)
    t.pendown()
    t.fillcolor("#DCAEE8")
    t.color("#DCAEE8")
    t.begin_fill()
    t.circle(40)
    t.end_fill()
    t.penup()
    t.goto(-15,15)
    t.pendown()
    for i in range(4):
        t.forward(10)
        t.left(90)
        
        t.forward(5) #first anteena
        t.left(45)
        t.forward(5)
        t.right(90)
        t.fillcolor("grey")
        t.color("grey")
        t.begin_fill()
        t.circle(2.5)
        t.end_fill()
        t.right(90)
        t.forward(5)
        t.right(45)
        t.forward(5)
        t.left(90)
        
        t.forward(10)
        t.left(90)
        
        t.forward(5) #second antena
        t.right(45)
        t.forward(5)
        t.right(90)
        t.fillcolor("grey")
        t.color("grey")
        t.begin_fill()
        t.circle(2.5)
        t.end_fill()
        t.right(90)
        t.forward(5)
        t.left(45)
        t.forward(5)
        t.left(90)
        t.forward(10)
        t.right(90)

    t.fillcolor('darkblue')
    t.color("darkblue")
    t.begin_fill()
    for i in range(4):
        t.forward(30)
        t.right(90)
    t.end_fill()

    t.penup()
    t.forward(10)
    t.right(90)
    t.forward(10)
    t.goto(0,0)
    t.pendown()

    t.fillcolor("red")
    t.color('red')
    for i in range(10):
        t.begin_fill()
        t.circle(2)
        t.right(36)
        t.end_fill()
        
def middle():
    t.goto(0,0)
    t.fillcolor("orange")
    t.color("orange")
    for i in range(24):
        t.begin_fill()
        for j in range(4):
            t.forward(40)
            t.right(90)
        t.end_fill()
        t.right(15)

def big():
    t.goto(0,0)
    for i in range(12):
        t.fillcolor("orange")
        t.color("orange")
        t.begin_fill()
        for j in range(4):
            t.forward(65)
            t.right(90)
        t.end_fill()
        t.right(15)
        t.fillcolor("brown")
        t.color("brown")
        t.begin_fill()
        for j in range(4):
            t.forward(65)
            t.right(90)
        t.end_fill()
        t.right(15)
    t.penup()
    t.goto(0,-80)
    t.pendown()    
    t.fillcolor("#FFF0CD")
    t.color("#FFF0CD")
    t.begin_fill()
    t.circle(80)
    t.end_fill()
    t.penup()
    t.goto(0,-70)
    t.pendown()    
    t.fillcolor("green")
    t.color("green")
    t.begin_fill()
    t.circle(70)
    t.end_fill()
    t.penup()
    t.goto(0,-60)
    t.pendown()    
    t.fillcolor("yellow")
    t.color("yellow")
    t.begin_fill()
    t.circle(60)
    t.end_fill()

def layer1():
        t.goto(0,0)
        for i in range(6):
            t.fillcolor("orange")
            t.color("orange")
            t.begin_fill()
            for j in range(4):
                t.forward(85)
                t.right(90)
            t.end_fill()
            t.right(30)
            t.fillcolor("yellow")
            t.color("yellow")
            t.begin_fill()
            for j in range(4):
                t.forward(85)
                t.right(90)
            t.end_fill()
            t.right(30)
        t.goto(0,0)
        for i in range(6):
            t.fillcolor("pink")
            t.color("pink")
            t.begin_fill()
            for j in range(4):
                t.forward(75)
                t.right(90)
            t.end_fill()
            t.right(30)
            t.fillcolor("red")
            t.color("red")
            t.begin_fill()
            for j in range(4):
                t.forward(75)
                t.right(90)
            t.end_fill()
            t.right(30)

def layer2():
    t.penup()
    t.goto(0,-130)
    t.left(90)
    t.fillcolor("#FFF0CD")
    t.color("#FFF0CD")
    t.begin_fill()
    t.circle(130)
    t.end_fill()
    t.goto(0,-120)
    t.fillcolor("#016B0F")
    t.color("#016B0F")
    t.begin_fill()
    t.circle(120)
    t.end_fill()

def text():
    t.penup()#C
    t.goto(-200,200)
    t.pendown()
    t.right(180)
    t.forward(30)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(30)

    t.penup()#O
    t.goto(-195,200)
    t.pendown()
    for i in range(4):
        t.forward(30)
        t.right(90)

    t.penup()#D
    t.goto(-160,200)
    t.right(90)
    t.pendown()
    t.forward(30)
    t.left(90)
    t.forward(20)
    t.left(45)
    t.forward(((2**(1/2))*10))
    t.left(45)
    t.forward(10)
    t.left(45)
    t.forward(((2**(1/2))*10))
    t.left(45)
    t.forward(20)

    t.penup()#E
    t.goto(-125,200)
    t.pendown()
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(30)
    t.penup()
    t.goto(-95,200)
    t.pendown()
    t.right(180)
    t.forward(30)
    t.left(90)
    t.forward(15)
    t.left(90)
    t.forward(20)

    t.penup()#A
    t.goto(-60,200)
    t.pendown()
    t.forward(30)
    t.right(90)
    t.forward(30)
    t.right(180)
    t.forward(15)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(15)
    t.right(180)
    t.forward(30)

    t.penup()#P
    t.goto(5,200)
    t.pendown()
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(15)
    t.right(180)
    t.forward(30)
    t.right(180)
    t.forward(30)

    t.right(90)#OO
    for i in range(40,76,35):
        t.penup()
        t.goto(i,200)
        t.pendown()
        for i in range(4):
            t.forward(30)
            t.right(90)
            
    t.penup()#K
    t.goto(110,200)
    t.pendown()
    t.right(90)
    t.forward(30)
    t.goto(110,185)
    t.goto(140,200)
    t.goto(110,185)
    t.goto(140,170)

    t.penup()#A
    t.left(90)
    t.goto(145,200)
    t.pendown()
    t.forward(30)
    t.right(90)
    t.forward(30)
    t.right(180)
    t.forward(15)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(15)
    t.right(180)
    t.forward(30)

    t.penup()#L
    t.goto(180,200)
    t.pendown()
    t.right(180)
    t.forward(30)
    t.left(90)
    t.forward(30)

    t.penup()#A
    t.left(90)
    t.goto(215,200)
    t.pendown()
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(30)
    t.right(180)
    t.forward(15)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(15)
    t.right(180)
    t.forward(30)

    t.penup()#M
    t.goto(250,170)
    t.down()
    t.forward(30)
    t.goto(265,185)
    t.goto(280,200)
    t.right(180)
    t.forward(30)
    
def text2():
    t.penup()#E
    t.goto(-270,-200)
    t.pendown()
    t.forward(30)
    t.left(90)
    t.forward(30)
    t.penup()
    t.goto(-240,-200)
    t.pendown()
    t.right(180)
    t.forward(30)
    t.left(90)
    t.forward(15)
    t.left(90)
    t.forward(20)

    t.penup()#L
    t.goto(-235,-200)
    t.pendown()
    t.right(90)
    t.forward(30)
    t.left(90)
    t.forward(30)

    t.penup()#E
    t.goto(-200,-200)
    t.pendown()
    t.right(90)
    t.forward(30)
    t.left(90)
    t.forward(30)
    t.penup()
    t.goto(-170,-200)
    t.pendown()
    t.right(180)
    t.forward(30)
    t.left(90)
    t.forward(15)
    t.left(90)
    t.forward(20)
    
    t.penup()#C
    t.goto(-135,-200)
    t.pendown()
    t.right(180)
    t.forward(30)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(30)

    t.penup()#T
    t.goto(-130,-200)
    t.pendown()
    t.forward(30)
    t.penup()
    t.goto(-115,-200)
    t.pendown()
    t.right(90)
    t.forward(30)

    t.penup()#R
    t.goto(-95,-200)
    t.pendown()
    t.left(90)
    t.forward(30)
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(15)
    t.right(180)
    t.forward(30)
    t.right(180)
    t.forward(30)
    t.right(180)
    t.forward(15)
    t.goto(-65,-230)

    t.penup()#O
    t.goto(-60,-200)
    t.pendown()
    t.left(90)
    for i in range(4):
        t.forward(30)
        t.right(90)

    t.penup()#N
    t.goto(-25,-230)
    t.pendown()
    t.left(90)
    t.forward(30)
    t.goto(5,-230)
    t.forward(30)

    t.penup()#I
    t.goto(10,-200)
    t.pendown()
    t.right(90)
    t.forward(30)
    t.penup()
    t.goto(10,-230)
    t.pendown()
    t.forward(30)
    t.right(90)
    t.penup()
    t.goto(25,-200)
    t.pendown()
    t.forward(30)

    
    t.penup()#C
    t.goto(75,-200)
    t.pendown()
    t.right(90)
    t.forward(30)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(30)

    t.penup()#O
    t.goto(110,-200)
    t.pendown()
    for i in range(4):
        t.forward(30)
        t.right(90)

    t.penup()
    t.goto(145,-230)
    t.pendown()
    t.left(90)
    t.forward(30)
    t.goto(175,-230)
    t.forward(30)
    
    t.penup()#A
    t.goto(180,-200)
    t.pendown()
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(30)
    t.right(180)
    t.forward(15)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(15)
    t.right(180)
    t.forward(30)

    t.penup()#M
    t.goto(215,-230)
    t.down()
    t.forward(30)
    t.goto(230,-215)
    t.goto(245,-200)
    t.right(180)
    t.forward(30)

t.speed(0)


text()
layer2()
layer1()
big()
middle()
eye()
text2()

t.hideturtle()
turtle.done()
